### ISSUE TITLE
vim9script

### ISSUE THREAD

**Issue by benknoble** [henriquehbr/lua-vs-vimscript#1]
For the record, the following `config.vim` run in vim 8.2.2300 (`vim --noplugin --clean --startuptime results.txt -u config.vim`) takes 176ms total, of which roughly 150ms are the script. Timings this small should really be run repeatedly and analyzed for accurate results, though (which I would argue is also an issue with the current benchmark).

```
vim9script

def VimNew(): number
  var sum: number = 0
  for i in range(1, 2999999)
    sum = sum + i
  endfor

  return sum
enddef

defcompile
VimNew()
```

**Comment by henriquehbr** [comment]
Indeed, this benchmark is really, really simple and on most cases, at first, it's main purpose was solely convincing myself on migrating to Lua, there's even a great point on [this](https://www.reddit.com/r/neovim/comments/oqi34r/lua_vs_vimscript_benchmark/h6cd95a?utm_source=share&utm_medium=web2x&context=3) comment on post i made on Reddit explaining why these test cases have nothing to do with real life scenarios

Do you think using a better benchmarking tool like [hyperfine](https://github.com/sharkdp/hyperfine) as a first step to improving the consistency and credibility of the results is a good solution?

**Comment by benknoble** [comment]
Seems reasonable /shrug. I don't have a ton of interest in doing a lot of benchmarks, just happened to see this and was curious about the results.

**Comment by henriquehbr** [comment]
Actually, relying on (n)vim builtin `--startuptime` flag would be a better option in this case, as it provides a more trustworthy startup time feedback in contrast to a more general-purpose tool, i will refactor the benchmark script for executing multiple runs for each test case
